### ISSUE TITLE
ccb cookie怎么抓啊哥= =

### ISSUE THREAD

**Issue by juner922** [pujie1216/CCBExchange#1]
属实一直不知道怎么抓取，请赐教

**Comment by juner922** [comment]
说错了是龙卡星期六的，Seccode 这个数据不知道如何抓取

**Comment by pujie1216** [comment]
呃，教程在这里不好说。。。

**Comment by juner922** [comment]
老哥发个企鹅或者vx&nbsp; 也可以。。ccb我是会抓，就是建行星期六不会抓中间那个参数 token跟cookie都会




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "pujie1216/CCBExchange"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月4日(星期五) 下午3:21
收件人:&nbsp;"pujie1216/CCBExchange"<CCBExchange@noreply.github.com&gt;;
抄送:&nbsp;"背过手๑"<1192150@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [pujie1216/CCBExchange] ccb cookie怎么抓啊哥= = (#1)





 
呃，教程在这里不好说。。。

**Comment by pujie1216** [comment]
神秘数字

**Comment by pujie1216** [comment]
solved
